name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write # Needed for JSR publish
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<actions@github.com>"

      - name: Get version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(cat deno.json | jq -r '.version')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Validate version format
        run: |
          if ! [[ "${{ steps.get_version.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.\-]+)?$ ]]; then
            echo "Invalid version format: ${{ steps.get_version.outputs.version }}"
            exit 1
          fi

      - name: Publish to JSR
        run: |
          deno publish --allow-dirty --scope=${{ github.repository_owner }}
        env:
          DENO_VERSION: ${{ steps.get_version.outputs.version }}
          JSR_NAMESPACE: ${{ github.repository_owner }}
